

service: tnw-backend

# app: Taste Not Waste
# org: TR_Bees

provider:
  name: aws
  runtime: nodejs10.x
  region: eu-west-2

functions:
  favourite:
    handler: handler.favourite
    environment:
      DB_HOST: ${opt:DB_HOST}
      DB_USER: ${opt:DB_USER}
      DB_PASSWORD: ${opt:DB_PASSWORD}
    events:
      - http:
          path: favourite
          method: get
          cors: true
      - http:
          path: tasks
          method: post
          cors: true
#      - http:
#          path: tasks/{taskId}
#          method: delete
#          cors: true
#      - http:
#          path: tasks/{taskId}
#          method: put
#          cors: true